Feat/#108 신고 기능 구현
coffee-meet/backend pull request #118
Opened 2023-11-18 04:34 UTC by 1o18z

## 이슈번호

close: #108

## 작업 내용 설명

- [x] 신고 생성 및 저장 기능 구현
- [x] 신고 조회 기능 구현
- 동일 채팅방 내의 동일 타겟에 대한 신고가 여러건일 경우 전체 조회 시 하나의 신고로 조회
- 타겟 아이디로 조회할 경우 동일 채팅방의 모든 신고 내역 조회
- 신고 아이디로 조회할 경우 해당 신고 내역 조회
- [x] 신고 도메인 테스트 코드 작성
- [x] ReportRepository
- [x] ReportQueryTest
- [x] ReportCommandTest
- [x] ReportServiceTest
- [ ] ReportControllerTest
## 리뷰어에게 한마디

2023-11-18 08:23 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/domain/ReportReason.java
> +    };
valueOf() 쓰는거 어떨까요??

음... 예를 들어서

```
  public static ReportReason getReason(String reason) {
    ReportReason.valueOf(reason.replaceAll(" ", "_"))
  }
```

2023-11-18 08:23 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/domain/Report.java
> +  private ReportReason reason;
`@Column(nullable = false)` 추가해주세요

2023-11-19 07:18 UTC, yumyeonghan approved these changes
수고하셨습니다!

2023-11-20 06:06 UTC, smart-sangmin requested changes

2023-11-20 08:51 UTC, smart-sangmin requested changes

2023-11-20 08:51 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/implement/ReportQuery.java
> +  }
Optional api 사용해서 처리 해주세요

2023-11-20 08:51 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/infrastructure/ReportRepository.java
> +      long targetId);
targetUser던가 targeter 같은 걸로 하면 좋을거 같은데 어떻게 생각하세용?

2023-11-20 08:51 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/service/ReportService.java
> +  }
따로 얘기 나눴던 방향으로 변경 부탁드립니다~!

2023-11-20 08:51 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/service/ReportService.java
> +    User reporter = userQuery.getUserById(report.getReporterId());
쿼리 하나하나 날리지 말로 한 번에 가져오는게 좋다고 생각됩니다! 이러면 N+1과 동일한 성능 상의 문제가 발생하는 것 같습니다

2023-11-20 08:51 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/service/ReportService.java
> +    User targetUser = userQuery.getUserById(report.getTargetId());
쿼리 하나하나 날리지 말로 한 번에 가져오는게 좋다고 생각됩니다! 이러면 N+1과 동일한 성능 상의 문제가 발생하는 것 같습니다

2023-11-20 16:30 UTC, yumyeonghan approved these changes
수고하셨습니다.!

2023-11-20 16:30 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/common/util/Patterns.java
> +  public static final Pattern REPORT_REASON_PATTERN = Pattern.compile(" ");
다른 도메인에서도 사용 될 수 있으니, 네이밍을 좀 더 적절하게 하면 좋을거 같아요

2023-11-20 16:30 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/report/domain/ReportReason.java
> +  괴롭힘_또는_스토킹,
괴롭힘으로 통일하는것도 나쁘지 않은거 같아요

2023-11-20 16:34 UTC, smart-sangmin approved these changes
짝짝짝 수고하셨씁니다

2023-11-20 16:34 UTC, merged