Feat/#128 신고 내역 조회 API 작성
coffee-meet/backend pull request #136
Opened 2023-11-21 14:27 UTC by 1o18z

## 이슈번호

close: #128

## 작업 내용 설명

- [x] 신고 내역 조회 API 작성
- [x] 테스트 코드 작성
## 리뷰어에게 한마디

2023-11-22 09:31 UTC, yumyeonghan reviewed
수고하셨씁니다!!

2023-11-22 09:31 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/report/infrastructure/ReportQueryRepository.java
>      // TODO: 11/20/23 order by, limit, offset 페이징 처리 추가
작업했다면, todo 주석 지워주세요~

2023-11-22 09:31 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
> +      @PageableDefault Pageable pageable
`@PageableDefault` default size 정해주세요~

2023-11-22 09:31 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
> +      @RequestParam Long targetedId
`@ModelAttribute` 사용하시는거 어떤가요?

2023-11-22 09:31 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
> +  public ResponseEntity<List<TargetReportHTTP.Response>> findReportByTargetIdAndChattingRoomId(
- TargetReportHTTP에 신고 사유 필드는 없어도 되나요?
- 직접 List 반환은 지양하는것이 좋아보여요.
    - List를 새로운 객체에 담아 응답하는 구조로 변경하면 좋을것같습니다!

2023-11-22 09:32 UTC, yumyeonghan approved these changes

2023-11-22 09:33 UTC, yumyeonghan commented
그리고 테스트 실패한거 확인 부탁드립니다!

2023-11-22 10:39 UTC, 1o18z commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
> +  public ResponseEntity<List<TargetReportHTTP.Response>> findReportByTargetIdAndChattingRoomId(
TargetReportHTTP에는 신고자 닉네임과 날짜만 보여지고 클릭하면 (신고 사유를 포함한) 상세 내용이 보여지게 되어 있는데 여기도 신고 사유를 보이게 하는게 좋을까용? 🦭

2023-11-22 18:22 UTC, smart-sangmin requested changes
쑤꼬하셨씁니따!

2023-11-22 18:22 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
>      }
저희가 정의한 `HTTP.Response`에 대해 저는 응답 JSON과 1:1 매핑되는 객체라고 생각합니다.

은지님 로직에서는 `List<GroupReportHTTP.Response(단수)>` 를 감싸는 `GroupReportsHTTP.Response(복수)` 가 있는 걸로 파악됩니다.

`GroupReportHTTP.Response(단수)` 는 응답 JSON과 1:1 매핑 되는 것이 아닌 응답 JSON 내부 필드로 있는데 내부 필드로 있을 객체를 HTTP.Response 라는 네이밍 말고 따로 정의하는 것이 어떨까요??

2023-11-22 18:22 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/presentation/dto/GroupReportHTTP.java
> +public final class GroupReportHTTP {
이전에 드린 리뷰에서 추가하면 이 객체에서는 Request라는 객체가 생길 수가 없을 것 같는데 맞나요?

2023-11-22 18:22 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/report/presentation/dto/CreateReportHTTP.java
> +public final class CreateReportHTTP {
객체 생성을 막기 위한 NoArgsConstructor(access=PRIVATE) 추가해주세요!

웹 모델 객체에 대부분 빠져있네요

2023-11-22 20:52 UTC, smart-sangmin commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
> +            @PageableDefault Pageable pageable
찾아보니 `Pageable` 의 최대 size는 2000까지 가능하네요

저희는 2000까지는 필요하지 않으니 DTO 로 받아서 처리하거나 CustomHandler를 작성하면 좋을 것 같습니다!

아래는 Pageable을 처리하는 Handler입니다!

![스크린샷 2023-11-23 오전 5 51 19](https://github.com/coffee-meet/backend/assets/70051888/2c8d352b-6f1e-4f55-a623-abc10c380cff)

2023-11-22 21:40 UTC, smart-sangmin commented on src/test/java/coffeemeet/server/admin/presentation/AdminControllerTest.java
> +                                fieldWithPath("empty").type(JsonFieldType.BOOLEAN).description("데이터가 비었는지 여부")
이거 전부 프론트한테 보내주는 것보다는 Page 객체를 따로 정의해서 보내주는게 좀 더 친절한 응답값일 것 같은데 어떻게 생각하시나요?

2023-11-23 05:26 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
> +  public ResponseEntity<List<TargetReportHTTP.Response>> findReportByTargetIdAndChattingRoomId(
아 그런 흐름이면 없어도 될것같습니다!

2023-11-23 05:54 UTC, yumyeonghan commented on src/main/java/coffeemeet/server/admin/presentation/AdminController.java
> +            @PageableDefault Pageable pageable
추가적으로 Page를 직접 반환하는 것 보단, 클라이언트가 필요한 정보들만 넘기는 것이 좋아보여요!

2023-11-23 15:02 UTC, smart-sangmin approved these changes

2023-11-24 06:19 UTC, merged